# Generated by Django 3.1.5 on 2021-01-20 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_course_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Название статьи'),
        ),
    ]
