# Generated by Django 3.1.5 on 2021-01-20 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20210120_1108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['course_url'], 'verbose_name': 'Ссылка на статью', 'verbose_name_plural': 'Ссылки на статьи'},
        ),
    ]
